### ISSUE TITLE
Hotspot is not active even if it shows that it is.

### ISSUE THREAD

**Issue by ohtoyeyejke** [prafulla-codes/react-native-wifi-and-hotspot-wizard#27]
When I turn on the hotspot and put SSID and Password, it says "Hotspot is now Active" but when I search for it from other devices it actually doesn't exist.

After some hours of debugging I couldn't resolve the issue so I am posting it here.

**Comment by prafulla-codes** [comment]
Hi, I beleive the hotspot created using this library is only available for application layer communication.

Meaning, you can't directly connect it normally to share the data etc
